blog2/urls.py
from django.contrib import admin
from django.urls import path,include

from main.views import main
from django.conf.urls.static import static
from django.conf import settings
from takip.views import add_fallow_or_delete
from django.urls import path, register_converter
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', main),
    path('be9232c.txt/',include("mail.urls")),

    path('order/',include("orders.urls")),
    path('gonderi/',include("gonderi.urls")),
    path('bakiye_ekle/',include("bakiye.urls")),

    path('auths/',include("auths.urls")),
    path('project/',include("post.urls")),
    path('shop/',include("shop.urls")),
    path('fonlama/',include("fonlamalar.urls")),
    path('haberler/',include("haberler.urls")),

    path('fallowing/',include('takip.urls',namespace='fallowing')),

    path('product/',include("products.urls")),

    path('tanitim/',include("tanitim.urls")),
    path('odeme/',include("odeme.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gonderi/urls.py
from django.urls import path,re_path
from .views import *


app_name="gonderi"

urlpatterns = [
    
   
    path('', gonderiler_index , name='gonderi'),
    path('addcomment/<int:id>', addcomment , name='addcomment'),

    path('create', gonderi_create,name="create"),


]
    

mail/urls.py
from django.urls import path,re_path,include
from .views import *

app_name="mail"

urlpatterns = [
    
    path('',mail,name="mail"),
    

]

gonderi/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm,TextInput

# Create your models here.





class Gonderiler(models.Model):
    user = models.ForeignKey('auth.User',verbose_name="User",on_delete = models.CASCADE)
  


    content=RichTextField(verbose_name="Gönderinizi Giriniz")
    date=models.DateTimeField(verbose_name="Tarih",auto_now_add=True)
    image= models.ImageField(null=True,blank=True,verbose_name="Gönderinize Resim Ekleyebilirsiniz")
    
    


    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-date']


   
        








        
class Comment(models.Model):

    STATUS=(
        ('New','Yeni'),
        ('True','Evet'),
        ('Falsa','Hayır'),
    )

    gonderi=models.ForeignKey(Gonderiler,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    comment=models.CharField(max_length=120,blank=True)
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip=models.CharField(blank=True,max_length=20)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

class CommentForm(ModelForm):
    class Meta:
            model=Comment
            fields=['comment']   
    





gonderi/forms.py
from django import forms
from .models import Gonderiler
from .models import Comment
from django import forms


class GonderiForm(forms.ModelForm):
  
    class Meta:
        model=Gonderiler
        fields=[
            "content",
            "image",
        
        ]



gonderi/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,HttpResponseRedirect,redirect,Http404
from .forms import GonderiForm
from django.contrib import messages
from django.utils.text import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import Gonderiler,CommentForm,Comment
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django import forms
from haberler.models import *
# Create your views here.
def gonderiler_index(request):
    gonderi_list=Gonderiler.objects.all()
    paginator = Paginator(gonderi_list, 25) # Show 25 contacts per page
    popiler=popilerhaber.objects.filter()

    page = request.GET.get('page')
    try:
        gonderiler = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        gonderiler = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        gonderiler = paginator.page(paginator.num_pages)

    comments=Comment.objects.all()   
    context={
        "comments":comments,
        "gonderiler":gonderiler,
        "popiler":popiler,
    }
    
    return render(request,"gonderi/index.html",context)
    

def gonderi_create(request):
     
    if not request.user.is_authenticated:
         raise Http404()
    
    
    
  #( title=request.POST.get("title")
   # content=request.POST.get("content"
    #Post.objects.create(title=title, content=content) )

    
        #FORMU KAYDET
    form=GonderiForm(request.POST or None, request.FILES or None)
    if form.is_valid():
         
          gonderi=  form.save(commit=False)
          gonderi.user=request.user
          gonderi.save()
          messages.success(request,"Gönderi Gönderildi...")
          return HttpResponseRedirect('/gonderi/')
    
    context={
        "form": form,}
    return render(request,'gonderi/form.html',context)



@login_required(login_url='/login')
def addcomment(request,id):
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            current_user=request.user

            data=Comment()
            data.user_id=current_user.id
            data.gonderi_id=id
            data.comment=form.cleaned_data['comment']
            data.ip=request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request,"Yorumunuz Gönderildi")
            url=request.META.get('HTTP_REFERER')
            return render(request,'gonderi/yorumlar.html')


    return HttpResponse("Yorum Gönderilemedi")
    
    




   



templates/gonderi/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body  %}
{% load static %}
  		<link href="{% static 'css/createproject.css' %}" rel="stylesheet" type="text/css">
  		<link href="{% static 'css/navbar2.css' %}" rel="stylesheet" type="text/css">

<br>
<br>
<br>
<br>
<div id="yan1">
<img  src="/static/image/yan.png"  alt="form">
</div>
<br>
<div id="formr">

<div class="container">
<div class="row"></div>
<form method="post" enctype="multipart/form-data">
{% csrf_token %}

       
    {{form|crispy}}
    {{form.media}}
    <input class="btn btn-primary" type="submit" value="Paylaş">


</form>
</div>
</div>







{% endblock  %}

templates/gonderi/index.html
{% extends 'base.html' %}
{% block title %}
<title>Gönderiler | MindUni</title>
{% endblock title %}
{% block body %}

<link rel="stylesheet" type="text/css" href="/static/navig/base.98fd6c19.css">
	<link href="/static/js/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script type="text/javascript" rel="script" src="/static/js/jquery-3.5.1.min.js"></script>
<script type="text/javascript" rel="script" src="/static/js/jquery-3.5.1.js"></script>
 <link rel="stylesheet" href="/static/pi/css/base.css">
  <link rel="stylesheet" href="/static/css/gonderiler.css">
<link href="/static/js//bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/jquery-3.2.1.min.js"></script>
<!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="/static/pi/css/base.css">
    <link rel="stylesheet" href="/static/pi/css/vendor.css">


<center>

<div id="createp">
 <a href="create">
                                   <img src="/static/image/gonderi.png" alt="">
                                   </a>
                                   </div>
                                   <div id="haberler">
 <a href="/haberler">
                                   <img src="/static/image/haberler.png" alt="">
                                   </a>

 </div>

<div id="createmobil">
<a href="create">
                                   <img src="/static/image/gonderimobil.png" alt="">
                                   </a>
                                   </div>
                                   <div id="haberlermobil">
                                   <a href="/haberler">
                                   <img src="/static/image/haberlermobil.png" alt="">
                                   </a>
                                   </div>
                                  


<div id="yeri">

<div  class="container">

{% for gonderi in gonderiler  %}

    <div class="row">

        <div class="col-xl-12">
                    
                        
                    <div class="wrap-login100">
				            <div class="login100-form-title" >
                            
                                        <img src="{{gonderi.user.userprofile.get_foto}}" alt="Userphoto" class="wp-image-2737 tie-appear" width="60" height="60">
                            <br>
                


                                {{gonderi.user}}
               
<div id="buton" >

<div class="btn-group">
  <button type="button" class="btn  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
  </button>
  <div class="dropdown-menu">
  	{% if  request.user == gonderi.user %} 

    <a class="dropdown-item" href="#">Düzenle</a>
    <a class="dropdown-item" href="#">Paylaş</a>
    <a class="dropdown-item" href="#">Favorilere Ekle</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Gönderiyi Şikayet Et</a>
  </div>
  {% endif %}
  {% if  request.user != gonderi.user %} 

    <a class="dropdown-item" href="#">Mesaj At</a>
    <a class="dropdown-item" href="#">Paylaş</a>
    <a class="dropdown-item" href="#">Favorilere Ekle</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Gönderiyi Şikayet Et</a>
  </div>
  {% endif %}
</div>
                            </div>  

                            </div>  
                            {% if gonderi.image %}
                                  <div id="gondeto">    
                                    
      <img class="d-block w-100" src="{{gonderi.image.url}}" alt="Gonderi Foto"   >
      </div>                            

       <br>                           
 
  

                         
                            {% endif %}  



<div id="contenty">

{{gonderi.content|safe}}
</div>

{% block yorum %}



{% endblock yorum %}
  

</div>
<br>
<br>
<br><br>
<br>
<br>
{% endfor %}
</div>
                                        </center>
<br>
<br>
<br>

<!-- s-extra
    ================================================== -->


<center>    
    <section class="s-extra">

        <div class="row">

            <div class="col-seven md-six tab-full popular">
                <h3>Popüler Haberler</h3>

                <div class="block-1-2 block-m-full popular__posts">

				{% for popiler in popiler %}
                    <article class="col-block popular__post">
                        <a href="#0" class="popular__thumb">
                            <img src="{{popiler.haber.image.url}}" alt="">
                        </a>
                        <a href="{{popiler.haber.get_absolute_url}}"><h5>{{popiler.haber.title}}</h5></a>
                        <section class="popular__meta">
                            <span class="popular__date"><span></span> <time datetime="2018-06-14">{{popiler.haber.create_at}}</time></span>
                        </section>
                    </article>
                {% endfor %}
                    
                </div> <!-- end popular_posts -->
            </div> <!-- end popular -->

            <div class="col-four md-six tab-full end">
                <div class="row">
                    <div class="col-six md-six mob-full categories">
                        <h3>Kategoriler</h3>
        
                        <ul class="linklist">
                            <li><a href="#0">Teknoloji</a></li>
                            <li><a href="#0">Girişim</a></li>
                            <li><a href="#0">Sosyal Yardım</a></li>
                            
                           
                        </ul>
                    </div> <!-- end categories -->
        
                    <div class="col-six md-six mob-full sitelinks">
                        <h3>Site Bağlantıları</h3>
        
                        <ul class="linklist">
                            <li><a href="/">Ana Sayfa</a></li>
                            <li><a href="/auths/profile/">Projeler</a></li>
                            <li><a href="#0">Fikirler</a></li>
                            <li><a href="#0">Bağış Sayfası</a></li>
                            <li><a href="#0">Mağaza</a></li>
                            <li><a href="#0">İletişim</a></li>
                            <li><a href="#0">Okullar/Takımlar</a></li>
                        </ul>
                    </div> <!-- end sitelinks -->
                </div>
            </div>
        </div> <!-- end row -->
    
    
    </section> <!-- end s-extra -->

</center>    
</body>




<div id="bodyalt">   
    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">
                
                

                <div class="col-six tab-full s-footer__subscribe">
                        
                    <h4>Yeni Proje Ve Fikirlerden Haberdar Olun</h4>

                    <p>E-Mail Üzerinden Yeni Proje Ve Fikirlerden Haberdar Olmak İsterseniz Aşağıdaki Formu Doldurabilirsiniz</p>
                    <small>*İstediğiniz zaman aboneliğinizi iptal edebilirsiniz.</small>

                    <div class="subscribe-form">
                        <form id="mc-form" class="group" novalidate="true">

                            <input type="email" value="" name="EMAIL" class="email" id="mc-email" placeholder="Email Addresi" required="">
                
                            <input type="submit" name="subscribe" value="Abone Ol">
                
                            <label for="mc-email" class="subscribe-message"></label>
                
                        </form>
                    </div>


                </div> <!-- end s-footer__subscribe -->

            </div>
        </div> <!-- end s-footer__main -->
</body>
        <div  class="s-footer__bottom">
        
            <div class="row">

                <div class="col-six">
                    <ul class="footer-social">
                       
                        <li>
                            <a href="#0"><i class="fab fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#0"><i class="fab fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#0"><i class="fab fa-youtube"></i></a>
                        </li>
                        
                    </ul>
                </div>

                <div class="col-six">
                    <div class="s-footer__copyright">
                        <span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> MindUni Bir KRC Projesidir <i class="fa fa-heart" aria-hidden="true"></i>  <a href="https://colorlib.com" target="_blank"></a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</span>
                    </div>
                </div>
                
            </div>
        </div> <!-- end s-footer__bottom -->

        <div class="go-top">
            <a class="smoothscroll" title="Back to Top" href="#top"></a>
        </div>

    </footer>



{% endblock body %}

templates/gonderi/yorumlar.html
{% block yorum %}
                        <form class="review-form" action="/gonderi/addcomment/{{gonderi.id}}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                            <textarea class="input" name="comment" id="id_comment" placeholder="Your rewiew"></textarea>
                            </div>
                                <button class="primary-btn">yolla</button>
                        </form>
{% endblock yorum %}